authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Regex support for validated ASCII, Latin1, UTF-8, UTF-16, UTF-32 and other encodings"
keywords = ["Strings", "Regex", "PCRE", "Unicode"]
license = "MIT"
name = "StrRegex"
uuid = "2267b70d-4c4a-5da2-8395-98751c0d506a"
version = "1.0.2"

[deps]
ModuleInterfaceTools = "5cb8414e-7aab-5a03-a681-351269c074bf"
PCRE2   = "c9310f65-a42c-5928-aca3-d34f64192029" # d62uhoik906m7n8r
MurmurHash3 = "b10b62ed-fbae-5ea5-b934-abaf0477b71d"
StrAPI = "69e7dfc3-c4d0-5e14-8d95-d6042a05b383"
CharSetEncodings = "cb9422de-a9d8-5b68-86db-ff05833ab307"
ChrBase = "c13fa7b1-fb91-5a40-8b3c-3aad7fd30002"
StrBase = "e79e7a6a-7bb1-5a4d-9d64-da657b06f53a" # 2v12uwlr0ueale6n

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
Random  = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Unicode", "Random"]

[compat]
julia = "^1.0.0"
ModuleInterfaceTools = "≥ 1.0.1"
StrAPI = "≥ 1.0.0"
MurmurHash3 = "≥ 1.0.1"
PCRE2 = "≥ 1.0.2"
ChrBase = "≥ 1.0.0"
CharSetEncodings = "≥ 1.0.0"
StrBase = "≥ 1.0.0"
