authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Regex support for validated ASCII, Latin1, UTF-8, UTF-16, UTF-32 and other encodings"
keywords = ["Strings", "Regex", "PCRE", "Unicode"]
license = "MIT"
name = "StrRegex"
uuid = "128fb37e-e16c-4908-8083-6410b01968ef"

[deps]
Pkg     = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test    = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

StrBase = "e79e7a6a-7bb1-5a4d-9d64-da657b06f53a" # 2v12uwlr0ueale6n
PCRE2   = "c9310f65-a42c-5928-aca3-d34f64192029" # d62uhoik906m7n8r
